### ISSUE TITLE
The .mat file is broken

### ISSUE THREAD

**Issue by ciwei123** [vztu/RAPIQUE#1]
@vztu Thanks for your sharing.When I want to load the feature file provided, I meet the error:
using MatlabR2019b：
错误使用 load
无法读取 MAT 文件 \RAPIQUE-main\feat_files\YOUTUBE_UGC_RAPIQUE_feats.mat。不是二进制 MAT 文件。请尝试执行 load
-ASCII 以便以文本形式读取。

using Python:
ValueError: Unknown mat file type, version 50, 51
Could you help me？Thank you very much!!!

**Comment by vztu** [comment]
This file is 30.3 MB in size. Please check whether you have downloaded it correctly.

If not, make sure you have enabled [git LFS](https://git-lfs.github.com/) and sync it again, or you can download manually.
