### ISSUE TITLE
The speed of the RAPIQUE？

### ISSUE THREAD

**Issue by ciwei123** [vztu/RAPIQUE#2]
@vztu Thanks for your sharing. I have read the paper《RAPIQUE: Rapid and Accurate Video Quality Prediction of User Generated Content》，and "TABLE IV" shows the RAPIQUE's runtime is 17.3. Could you explain the 17.3 for me in details ? I don't find the length of the 1080p video ?  17.3 specifies whether 17.3fps or 17.3 seconds for the whole 1080p video ? And because I find that the RAPIQUE is not end to end, does “17.3” include  "compute features time "？Thank you very much!!!

**Comment by vztu** [comment]
Thanks for asking.

It is 17.3 seconds on average for RAPIQUE feature extraction on **each** **entire** 1080p@10-second video from the LIVE-VQC dataset. You can check a few A00*.mp4 videos in LIVE-VQC, which are what we reported on.

**Comment by ciwei123** [comment]
@vztu Thanks for your reply. Does it means  the time is 17.3fps on 1080p@10-second for feature extraction？What about the time of other method provided in your paper? All mentioned times in your paper refer only to feature extraction time, excluding the regression score part? And the LIVE-VQC I downloaded is broken, only a few frames per video. Could you share the dataset according Baidudisk?Thank you very much!!

**Comment by vztu** [comment]
@ciwei123 

Does it means the time is 17.3fps on 1080p@10-second for feature extraction？No, it means 17.3 **seconds** on 1080p video.

What about the time of other method provided in your paper? "TABLE IV" shows runtime for all methods

The regression (inference) time is neglectable compared to feature extraction, so it is not considered here.

For LIVE-VQC, you can refer https://github.com/lidq92/VSFA/issues/30
