### ISSUE TITLE
File names are inconsistant between mos_files/LIVE_VQC_metadata.csv and LIVE VQC dataset.

### ISSUE THREAD

**Issue by easysam** [vztu/RAPIQUE#3]
I observe that the _File_ column in `mos_files/LIVE_VQC_metadata.csv` contains file names like "XXXNEW.mp4". However, there are no such "XXXNEW.mp4" files in the LIVE VQC dataset (only "XXX.mp4" can be found). Does the additional "NEW" straing makes a difference?

**Comment by vztu** [comment]
Hi, it doesn't make a difference. Just use whichever video named "XXX.mp4" or "XXXNEW.mp4," and you should be good to go. LIVE-VQC has some problems, so we might have pre-processed some videos. However, if you have 1 or 2 videos different from our copy, it doesn't matter that much and shouldn't affect your evaluation results.
